// 全局共用
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const REQUEST_ERROR = 'REQUEST_ERROR';
export const REQUEST_START = 'REQUEST_START';

//组件
export const GET_COMPONENTS_DATA = 'GET_COMPONENTS_DATA';
export const GET_CONTENT_DETAIL = 'GET_CONTENT_DETAIL';
export const SET_CONTENT_DETAIL_ID = 'SET_CONTENT_DETAIL_ID';
export const GET_FILTER_DATA = 'GET_FILTER_DATA';
export const SET_FILTER_INDEX = 'SET_FILTER_INDEX';
export const SET_INIT_COLLECTION = 'SET_INIT_COLLECTION';
export const INIT_PAGE_PARAMS = 'INIT_PAGE_PARAMS';

//SKU面板
export const SET_SKUPANEL_SHOW = 'SET_SKUPANEL_SHOW';
export const SET_SKUPANEL_INFO = 'SET_SKUPANEL_INFO';

//购物车相关
export const TOLTAL_PRICE = 'TOLTAL_PRICE';
export const CHECKED_ALL = 'CHECKED_ALL';
export const CHOOSE_ITEM = 'CHOOSE_ITEM';
export const UPDATE_SHOPCART = 'UPDATE_SHOPCART';
export const UPDATE_INVALID = 'UPDATE_INVALID';
export const UPDATE_PURCHASE_NUM="UPDATE_PURCHASE_NUM";

//订单详情相关
export const UPDATE_DETAILINFO='UPDATE_DETAILINFO'
export const SET_ORDER_LIST='SET_ORDER_LIST'

//创建订单相关
export const SET_DEFAULT_ADDRESS='SET_DEFAULT_ADDRESS'
export const SET_ORDERINFO='SET_ORDERINFO'
export const SET_CREATE_ORDERINFO='SET_CREATE_ORDERINFO'
export const SET_PAYSTATE='SET_PAYSTATE'
export const SET_EXTRA_INFO='SET_EXTRA_INFO'
export const SET_DYNAMIC_KEYMAPPING='SET_DYNAMIC_KEYMAPPING'

//地址列表相关
export const UPDATE_ADDRESSLIST='UPDATE_ADDRESSLIST'
export const DELETE_ADDRESSLIST='DELETE_ADDRESSLIST'
export const SET_CURRENT_ADDRESS='SET_CURRENT_ADDRESS'
export const SET_CURRENTAREA_CODE='SET_CURRENTAREA_CODE'

// 评论列表
export const GET_COMMENT_LIST ='GET_COMMENT_LIST';
export const FOCUS_KEYBOARD ='FOCUS_KEYBOARD';
export const SEND_COMMENT_LIST ='SEND_COMMENT_LIST';
export const SETTHUMB ='SETTHUMB';

// 关于我们
export const GET_ABOUT = 'GET_ABOUT';

// 评论样式
export const GET_COMMENT_STYLE='GET_COMMENT_STYLE';
export const SET_STARS='SET_STARS';


//搜索
export const GET_SEARCH_DATA = 'GET_SEARCH_DATA';
export const GET_SEARCH_HOTTAGS = 'GET_SEARCH_HOTTAGS';
export const SEARCH_ITEM = 'SEARCH_ITEM';

export const CANCEL_BACK = 'CANCEL_BACK';
export const CLEAR_HISTORY = 'CLEAR_HISTORY';


// 个人资料
export const PANEL_STATUS = 'PANEL_STATUS';
export const DEAL_NICKNAME_INFO = 'DEAL_NICKNAME_INFO';
export const SET_USER_INFO = 'SET_USER_INFO';
